# Generated by Django 4.0.6 on 2022-07-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contadorComputadora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEntrada', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('contadorMonitores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raton',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivoentrada')),
                ('contadorRatones', models.IntegerField()),
            ],
            bases=('dispositivos.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivoentrada')),
                ('contadorTeclados', models.IntegerField()),
            ],
            bases=('dispositivos.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadorOrdenes', models.IntegerField()),
                ('computadoras', models.ManyToManyField(to='dispositivos.computadora')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.monitor'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='raton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.raton'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.teclado'),
        ),
    ]
